# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
    ]
